### ISSUE TITLE
Image does not work on feed.

### ISSUE THREAD

**Issue by tylerhou** [jajanet/team-08-codeu#20]
Reproduction steps:

Go to your user page (https://su19-codeu-8-5472.appspot.com/user-page.html) for the current user (click from home).

Write a message with an image URL: https://d17fnq9dkz9hgj.cloudfront.net/breed-uploads/2018/09/dog-landing-hero-lg.jpg

Go to /feed.html.

Expected: I see an image.
Actual: I see a raw image HTML tag.

**Comment by jajanet** [comment]
fixed via dangerouslySetInnerHtml
